# -*- coding: utf-8 -*-
"""2: Decision Tree Regression Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KU0NePkfiCg3RV0ZttQWkZyUVQ-zHoH
"""



from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
california_housing = fetch_california_housing(as_frame=True)

# Display the dataset description and first few rows
print(california_housing.DESCR)
display(california_housing.data.head())

from sklearn.model_selection import train_test_split
housing = fetch_california_housing()
x= housing.data
y= housing.target

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

dt_model=DecisionTreeRegressor(random_state=42)
lr_model=LinearRegression()

dt_model.fit(x_train, y_train)
lr_model.fit(x_train, y_train)
dt_prediction = dt_model.predict(x_test)
lr_prediction = lr_model.predict(x_test)



dt_mae = mean_absolute_error(y_test, dt_prediction)
lr_mae = mean_absolute_error(y_test, lr_prediction)

print(f"Decision Tree Mean Absolute Error: {dt_mae:.4f}")
print(f"Linear Regression Mean Absolute Error: {lr_mae:.4f}")

import matplotlib.pyplot as plt
models=['Decision Tree','Linear Regression']
mae_values=[dt_mae,lr_mae]
plt.plot(models,mae_values,marker='o')
plt.xlabel('Models')
plt.ylabel('Mean Absolute Error')
plt.title('Mean Absolute Error Comparison')
plt.grid(True)
plt.show()

