# -*- coding: utf-8 -*-
"""fraud_trancation_vs_legitimate_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10z2yt9FXXPFQv7Ez9P6nTWkG2lpIxRw0
"""

import pandas as pd
import sklearn
import tensorflow as tf

df=pd.read_csv('fraudTrain.csv', on_bad_lines='skip')

df

df.shape

df.info()

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

total=len(df)
print("Total tranaction:",total)

fraud_count=df['is_fraud'].sum()
legit_count=total-fraud_count

print("Fraudulent transaction:",fraud_count)
print("Legitimate transaction:",legit_count)

fraud_percentage=(fraud_count/total)*100
legit_percentage=(legit_count/total)*100

print("Fraudulent percentage:",fraud_percentage)
print("Legitimate percentage:",legit_percentage)

percentage = df['is_fraud'].value_counts(normalize=True) * 100
print(percentage)

#legitmate=99.3/fraud-0.6

import matplotlib.pyplot as plt

counts = df['is_fraud'].value_counts()

plt.figure()
counts.plot(kind='bar')

plt.title('Fraudulent vs. Legitimate Transactions')
plt.xlabel('Transaction Type')
plt.ylabel('Count')

plt.show()

import matplotlib.pyplot as plt
# Fixed: Use 'is_fraud' instead of 'category' to match the 'Legitimate' and 'Fraud' labels
counts = df['is_fraud'].value_counts()

plt.figure()
plt.pie(counts, labels=['Legitimate', 'Fraud'], autopct='%1.1f%%')

plt.title('Fraudulent vs. Legitimate Transactions')
plt.show()

X = df.drop(columns=['is_fraud', 'trans_num'])
y = df['is_fraud']

categorical_cols = X.select_dtypes(include=['object']).columns
numeric_cols = X.select_dtypes(exclude=['object']).columns

from pandas.core.indexes import category
import sklearn
from sklearn.preprocessing import LabelEncoder
category_cols = X.select_dtypes(include=['object']).columns

for col in category_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Using class_weight instead of resampling
class_weights = {0: 1, 1: 10}

df

df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

df['hour'] = df['trans_date_trans_time'].dt.hour
df['day'] = df['trans_date_trans_time'].dt.dayofweek

df[['trans_date_trans_time','hour','day']].head()

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

lr.fit(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train,y_train)

y_pred_lr = lr.predict(X_test)
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print("Logistic Regression Report:")
print(classification_report(y_test, y_pred_lr))

print("Random Forest Report:")
print(classification_report(y_test, y_pred_rf))

from sklearn.metrics import roc_auc_score

lr_probs = lr.predict_proba(X_test)[:,1]
rf_probs = rf.predict_proba(X_test)[:,1]

print("LR ROC-AUC:", roc_auc_score(y_test, lr_probs))
print("RF ROC-AUC:", roc_auc_score(y_test, rf_probs))

importances = rf.feature_importances_

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

feature_importance.head(10)

#task-2

y

















