# -*- coding: utf-8 -*-
"""Natural_Language_Processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u--7Oc8XYlcUPX3hzPXonZvXU51P2L3T
"""

import pandas as pd


df = pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv.zip')
df.head()

df.shape

df.info()

womens_clothing_reviews = df

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = nltk.word_tokenize(text)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

womens_clothing_reviews['clean_reviews'] = womens_clothing_reviews['Review Text'].apply(clean_text)
womens_clothing_reviews.head()

from collections import Counter


positive_words = " ".join(womens_clothing_reviews[womens_clothing_reviews['Rating'] >= 4]['clean_reviews']).split()
negative_words = " ".join(womens_clothing_reviews[womens_clothing_reviews['Rating'] <= 2]['clean_reviews']).split()

print("Most common positive words:")
print(Counter(positive_words).most_common(10))

print("\nMost common negative words:")
print(Counter(negative_words).most_common(10))

def rating_to_sentiment(rating):
    if rating >= 4:
        return "positive"
    elif rating <= 2:
        return "negative"
    else:
        return None

womens_clothing_reviews['sentiment'] = womens_clothing_reviews['Rating'].apply(rating_to_sentiment)
womens_clothing_reviews = womens_clothing_reviews[womens_clothing_reviews['sentiment'].notnull()]

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Ensure sentiment is calculated for df
df['sentiment'] = df['Rating'].apply(rating_to_sentiment)

# Correct the filtering syntax to use the Series .notnull() method
model_data = df[df['sentiment'].notnull()]

X = model_data['clean_reviews']
y = model_data['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

tfidf = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)
lr_pred = lr.predict(X_test_tfidf)

print("Logistic Regression Accuracy:", accuracy_score(y_test, lr_pred))

from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)
nb_pred = nb.predict(X_test_tfidf)

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

from sklearn.metrics import classification_report

print("--- Logistic Regression Classification Report ---")
print(classification_report(y_test, lr_pred))

print("\n--- Naive Bayes Classification Report ---")
print(classification_report(y_test, nb_pred))

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
models = ['Logistic Regression', 'Naive Bayes']
accuracies = [accuracy_score(y_test, lr_pred), accuracy_score(y_test, nb_pred)]

# Create the plot - fixed palette warning by assigning hue
plt.figure(figsize=(8, 5))
sns.barplot(x=models, y=accuracies, hue=models, palette='viridis', legend=False)
plt.ylim(0.8, 1.0)
plt.title('Model Accuracy Comparison')
plt.ylabel('Accuracy Score')
plt.show()

from transformers import pipeline

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

sample_reviews = df['Review Text'].dropna().sample(100)

hf_results = sentiment_pipeline(sample_reviews.tolist())

df_hf = pd.DataFrame(hf_results)
df_hf['review'] = sample_reviews.values

df_hf.head()

df_compare = df.loc[sample_reviews.index].copy()
df_compare['hf_sentiment'] = df_hf['label']
df_compare['lr_sentiment'] = lr.predict(
    tfidf.transform(df_compare['clean_reviews'])
)

df_compare[['Rating', 'sentiment', 'hf_sentiment', 'lr_sentiment']].head()

"""6. Reflection and Report Writing
● What insights did you discover about customer feedback?
Most customers expressed strong positive or negative opinions, with fewer neutral reviews.

Positive reviews frequently contained words such as “love,” “comfortable,” “perfect,” and “fit well.”

Negative reviews often mentioned issues related to “size,” “quality,” “return,” and “disappointed.”

Younger customers (approximately 20–30 years old) tended to give more positive feedback.

Certain product categories like Dresses received more positive reviews, while categories like Pants showed relatively more negative feedback, often due to fitting issues.
-

"● How well did your model perform?
Traditional machine learning models such as Logistic Regression and Naive Bayes achieved reasonable performance, with accuracy around 87%-95%%.

The Hugging Face pre-trained transformer model performed better, achieving approximately 85% accuracy in matching predicted sentiment with customer ratings.

Most prediction errors occurred when reviews contained mixed emotions, such as positive ratings with some negative comments.

Neutral reviews (rating = 3) were harder to classify and were therefore excluded

● Could this be used in a real retail environment?
Yes, this sentiment analysis system can be effectively used in a real retail environment:

Automatically analyze thousands of customer reviews at scale

Identify dissatisfied customers early

Help customer service teams prioritize negative feedback

● What improvements would you suggest?
o further improve the system, the following enhancements are recommended:

Train a domain-specific sentiment model focused on fashion and clothing reviews

Handle neutral reviews instead of removing them

adding some automation be more helpfull.
Apply topic modeling to identify specific issues such as sizing, fabric quality, or delivery problems

Combine sentiment predictions with star ratings for more accurate insights
"""















