# -*- coding: utf-8 -*-
"""random_forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4mlM8E7Fj_sfAPfNtFrqIDS9xqnp60l
"""

-import pandas as pd

import pandas as pd
import os

# Unzip the file
!unzip -o Kaggle-Vehicle-Problem-master.zip

# load the CSV files.
df = pd.read_csv('Kaggle-Vehicle-Problem-master/car data.csv')
df.head()

print(df.to_string())

df.head()

df.info()

df.shape

from sklearn.model_selection import train_test_split

# Calculate Car_Age from the Year column
df['Car_Age'] = 2020 - df['Year']

X = df[['Car_Age', 'Kms_Driven', 'Seller_Type', 'Transmission', 'Owner']]
y = df['Fuel_Type']

y

X

df['Fuel_Type'].value_counts()

df.groupby('Fuel_Type')['Kms_Driven'].mean()
df.groupby('Fuel_Type')['Year'].mean()

df['Car_Age'] = 2020 - df['Year']

X = pd.get_dummies(X, drop_first=True)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

print("Data encoded and scaled successfully!")

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(x_train_scaled, y_train)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 5, 10],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(x_train, y_train)

best_rf = grid.best_estimator_
grid.best_params_

y_pred = best_rf.predict(x_test)

from sklearn.metrics import accuracy_score, classification_report


accuracy = accuracy_score(y_test, y_pred)
print(f"Tuned Random Forest Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=best_rf.classes_,
            yticklabels=best_rf.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

importances = best_rf.feature_importances_
features = X.columns

importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

importance_df

importance_df.head(10).plot(
    kind='barh',
    x='Feature',
    y='Importance',
    legend=False
)
plt.gca().invert_yaxis()
plt.title("Top Feature Importances")
plt.show()

