# -*- coding: utf-8 -*-
"""timeseriesproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_wE8sARHaOZRslZ6YqE1v6lfCnlN1h1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from statsmodels.tsa.stattools import adfuller,kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

energy_data=pd.read_csv("/content/energy_data.csv")
energy_data.head()

energy_data.info()

energy_data['utc_timestamp']=pd.to_datetime(energy_data['utc_timestamp'],utc=True)

energy_data.set_index('utc_timestamp',inplace=True)
energy_data.sort_index(inplace=True)

energy_data.head()

fig, ax =plt.subplots(figsize=(15,10))
ax.plot(energy_data['load_new'])

ax.set_title("Raw data")
ax.legend()

plt.figure(figsize=(15,10))
plt.plot(energy_data["load_new"])
plt.title("Raw data")
plt.show()

energy_data_interpolated=energy_data.copy(deep='True')
energy_data_interpolated['load_new']=energy_data_interpolated['load_new'].interpolate(method='time')

energy_data_interpolated.head()

energy_data_interpolated.info()

energy_outlier_removal=energy_data_interpolated.copy(deep='True')
lower_bound=energy_outlier_removal['load_new'].rolling(window=15).mean() - 3*energy_outlier_removal['load_new'].rolling(window=15).std()
upper_bound=energy_outlier_removal['load_new'].rolling(window=15).mean() + 3*energy_outlier_removal['load_new'].rolling(window=15).std()
energy_outlier_removal['load_new'] = np.where(energy_outlier_removal['load_new'] > upper_bound, upper_bound,
                                      np.where(energy_outlier_removal['load_new'] < lower_bound, lower_bound,
                                               energy_outlier_removal['load_new']))

outliers=energy_outlier_removal[(energy_outlier_removal['load_new']<lower_bound)|(energy_outlier_removal['load_new']>upper_bound)]

outliers

rolling_mean=energy_outlier_removal['load_new'].rolling(window=15).mean()

rolling_mean

result=adfuller(energy_outlier_removal['load_new'])
if result [1] <= 0.05:
  print("The data is stationary")
else:
  print("The data is not stationary")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Data Loading and Preprocessing
energy_data=pd.read_csv("/content/energy_data.csv")
energy_data['utc_timestamp']=pd.to_datetime(energy_data['utc_timestamp'],utc=True)
energy_data.set_index('utc_timestamp',inplace=True)
energy_data.sort_index(inplace=True)

# Interpolation
energy_data_interpolated=energy_data.copy(deep='True')
energy_data_interpolated['load_new']=energy_data_interpolated['load_new'].interpolate(method='time')

# Outlier Removal
energy_outlier_removal=energy_data_interpolated.copy(deep='True')
lower_bound=energy_outlier_removal['load_new'].rolling(window=15).mean() - 3*energy_outlier_removal['load_new'].rolling(window=15).std()
upper_bound=energy_outlier_removal['load_new'].rolling(window=15).mean() + 3*energy_outlier_removal['load_new'].rolling(window=15).std()
energy_outlier_removal['load_new'] = np.where(energy_outlier_removal['load_new'] > upper_bound, upper_bound,
                                      np.where(energy_outlier_removal['load_new'] < lower_bound, lower_bound,
                                               energy_outlier_removal['load_new']))

plt.subplot(2,1,1)
plot_acf(energy_outlier_removal['load_new'],lags=10)
plt.subplot(2,1,2)
plot_pacf(energy_outlier_removal['load_new'],lags=10)
plt.show()

from statsmodels.tsa.arima.model import ARIMA

model=ARIMA(energy_outlier_removal['load_new'],order=(2,0,8))
model_fit=model.fit()



forecast=model_fit.forecast(steps=120)
forecast_index=pd.date_range(start=energy_outlier_removal.index[-1],periods=120,freq='h')

forecast.index=forecast_index
forecast

plt.figure(figsize=(15,10))
plt.plot(energy_outlier_removal['load_new'],label='original')
plt.plot(forecast,label='forecast')
plt.legend()
plt.show()

forecast.to_csv=pd.DataFrame()

energy_prophet = pd.DataFrame({
    'ds': energy_outlier_removal.index.to_series().dt.tz_localize(None),
    'y': energy_outlier_removal['load_new']
})
energy_prophet.head()

from prophet import Prophet
model=Prophet()
model.fit(energy_prophet)

energy_prophet

future_points=model.make_future_dataframe(periods=120,freq='h')
forecast=model.predict(future_points)

plt.figure(figsize=(30,10))
model.plot(forecast)
plt.show()

