# -*- coding: utf-8 -*-
"""timeseries2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-GXdDE228BMumvUhhchPB2kmcOxe6VF
"""

import pandas as pd
import numpy as np

data=pd.date_range("2024-01-01",periods=30,freq="D")

date=pd.date_range("2024-01-01",periods=30,freq="D")
data=np.random.randn(100,size=30)
df=pd.DataFrame(data,columns=["USD"],index=date)
df

df[:5:] =np.nan
df[20:25] =np.nan

df.isnull().sum()

df

df.plot()

import matplotlib.pyplot as plt
df_spline=df.interpolate(method="spline",order=2)

plt.plot(df.index,df["USD"],label="Original")
plt.plot(df_spline.index,df_spline,linestyle=":",label="spline")
plt.legend()
plt.show()

date= pd.date_range("2024-01-01",periods=30,freq="D")
data=np.random.randint(40,50,size=30)
df=pd.DataFrame(data,columns=["USD"],index=date)
df

np.random.randint(30,40,20)

df[11:12]=150
df[13:14]=-30
df.plot()

df["rm"]=df["USD"].rolling(3).mean()
df

df["rm"]=df["USD"].rolling(10).mean()
df["std"]=df["USD"].rolling(10).std()

upper=df["rm"] +3*df["std"]
lower=df["rm"] -3*df["std"]

outliers=df[(df["USD"] >upper)  | (df["USD"] < lower)]
outliers

upper

lower,upper

from sklearn.ensemble import IsolationForest

model = IsolationForest(contamination=0.02)
model.fit(df[['USD']])
df["outliers_iso"] =model.predict(df[["USD"]])
df["outliers_iso"]

plt.figure(figsize=(10,6))
plt.plot(df.index,df["USD"],label="actual")
plt.scatter(df.index,df["outliers_iso"],label="preducted")
plt.title("Actual vs Predicted")
plt.legend()
plt.show()

