# -*- coding: utf-8 -*-
"""unsupervied.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9dVa2Ur_pyU25gpQaYODmKeJSYVAN1h
"""

import pandas as pd

df=pd.read_csv("fraudTrain.csv")

df

df.dropna()

df.isnull().sum()

df.info()

y_true = df['is_fraud']

X_unsupervised = df.drop(columns=['is_fraud', 'trans_num'])

import pandas as pd

df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
df['hour'] = df['trans_date_trans_time'].dt.hour
df['day_of_week'] = df['trans_date_trans_time'].dt.dayofweek


df['amount'] = df['amt']


df['merchant_category_encoded'] = df['category'].astype('category').cat.codes
df['transaction_type_encoded'] = 0

selected_features = [
    'amount',
    'hour',
    'day_of_week',
    'merchant_category_encoded',
]


X_unsup = df[selected_features]
X_unsup.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_unsup)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

from sklearn.ensemble import IsolationForest

iso = IsolationForest(
    contamination=0.005,
    random_state=42
)

iso.fit(X_scaled)

anomaly_labels = iso.predict(X_scaled)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

import numpy as np

y_pred = np.where(anomaly_labels == -1, 1, 0)  # 1 = fraud

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_true, y_pred))
print(classification_report(y_true, y_pred))

import matplotlib.pyplot as plt

plt.scatter(X_pca[:,0], X_pca[:,1], c=y_pred, cmap='coolwarm', alpha=0.5)
plt.title("Anomaly Detection using Isolation Forest (PCA Projection)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

